### ISSUE TITLE
Jokes 

### ISSUE THREAD

**Issue by rettm64** [rettm64/hello-world#2]
1. What dance move does a used tissue do? It does the boogie!
(Laugh Track)

2. What did the hungry computer eat? Chips! One byte at a time!
(Laugh Track)

3. What do you call cheese that isn't yours? Nacho Cheese!
(Laugh Track)

**Comment by Adam-Klemann** [comment]
yup. it's bad. good work.
4. WHere does the King keep his armies? Answer: In his sleevies!
